/*
    Copyright or (c) or Copr. Project-Team S3 (Sound Signals and Systems) and
    Analysis/Synthesis team, Laboratory of Sciences and Technologies of Music and
    Sound (UMR 9912), IRCAM-CNRS-UPMC, 1 place Igor Stravinsky, F-75004 Paris
    * contributors : Antoine Falaize, Thomas Helie,
    * corresponding contributor: antoine.falaize@ircam.fr
    * date: 2016/12/31 12:47:34

    This has been geerated by Py which purpose is to generate C++
    code for the simulation of multiphysics system described by graph structures.

    This software is governed by the CeCILL-B license under French law and
    abiding by the rules of distribution of free software.  You can  use,
    modify and/ or redistribute the software under the terms of the CeCILL-B
    license as circulated by CEA, CNRS and INRIA at the following URL
    "http://www.cecill.info".

    As a counterpart to the access to the source code and  rights to copy,
    modify and redistribute granted by the license, users are provided only
    with a limited warranty  and the software's author,  the holder of the
    economic rights, and the successive licensors  have only  limited liability.

    In this respect, the user's attention is drawn to the risks associated
    with loading,  using,  modifying and/or developing or reproducing the
    software by the user in light of its specific status of free software,
    that may mean  that it is complicated to manipulate,  and  that  also
    therefore means  that it is reserved for developers  and  experienced
    professionals having in-depth computer knowledge. Users are therefore
    encouraged to load and test the software's suitability as regards their
    requirements in conditions enabling the security of their systems and/or
    data to be ensured and,  more generally, to use and operate it in the
    same conditions as regards security.

    The fact that you are presently reading this means that you have had
    knowledge of the CeCILL-B license and that you accept its terms.

    Created on 2016/12/31 12:47:34

    author: Antoine Falaize


===========================================================================

    This file was automatically generated by Py, date 2017/11/14 23:04:19.

    It contains the code for the simulation of system 'CLIPPER'.

===========================================================================
*/

#include "core.h"
//==========================================================================
// PUBLIC    
    //==========================================================================
    // Sample Rate
    void CLIPPER::set_sampleRate(float & value) {
        sampleRate = value;
        init();
    }
    void CLIPPER::set_sampleRate(double & value) {
        sampleRate = value;
        init();
    }
    //==========================================================================
    // Core update
    void CLIPPER::update(){    
        ud_x_update();
        set_x(_ud_x);
        ud_o_update();
        set_o(_ud_o);
        jactempFll_update();
        ijactempFll_update();
        Gl_update();
        jactempFnll_update();
        Gnl_update();
        Fnl_update();
        res_Fnl_update();    
        unsigned int iter_res_Fnl = 0;
        _step_Fnl = 1;
        while ((iter_res_Fnl<10) & (res_Fnl()>1e-09) & (step_Fnl()>1e-09)){    
            save_Fnl_update();
            jacGlnl_update();
            jacGnlnl_update();
            jacFnl_update();
            ijacFnl_update();
            ud_vnl_update();
            set_vnl(_ud_vnl);
            Gl_update();
            Gnl_update();
            Fnl_update();
            res_Fnl_update();
            step_Fnl_update();iter_res_Fnl += 1;
        }    
        ud_vl_update();
        set_vl(_ud_vl);
        dxH_update();
        z_update();
        y_update();
    }
    //==========================================================================
    // Acessors to Arguments, return vector<float>
    vector<float> CLIPPER::x_vector() const {    
        vector<float> v = vector<float>(1);    
        v[0] = *xC;    
        return v;
    }
    vector<float> CLIPPER::dx_vector() const {    
        vector<float> v = vector<float>(1);    
        v[0] = *dxC;    
        return v;
    }
    vector<float> CLIPPER::w_vector() const {    
        vector<float> v = vector<float>(3);    
        v[0] = *wd2_R;    
        v[1] = *wd2_gmin;    
        v[2] = *wd2;    
        return v;
    }
    vector<float> CLIPPER::u_vector() const {    
        vector<float> v = vector<float>(2);    
        v[0] = *uoutput;    
        v[1] = *uinput;    
        return v;
    }
    vector<float> CLIPPER::p_vector() const {    
        vector<float> v = vector<float>(0);    
        return v;
    }
    vector<float> CLIPPER::vl_vector() const {    
        vector<float> v = vector<float>(3);    
        v[0] = *dxC;    
        v[1] = *wd2_R;    
        v[2] = *wd2_gmin;    
        return v;
    }
    vector<float> CLIPPER::vnl_vector() const {    
        vector<float> v = vector<float>(1);    
        v[0] = *wd2;    
        return v;
    }
    vector<float> CLIPPER::o_vector() const {    
        vector<float> v = vector<float>(0);    
        return v;
    }
    //==========================================================================
    // Acessors to Arguments, return Matrix<float, n, m>
    Matrix<float,1, 1> CLIPPER::x() const {    
        Matrix<float,1, 1> m;    
        m(0, 0) = *xC;    
        return m;
    }
    Matrix<float,1, 1> CLIPPER::dx() const {    
        Matrix<float,1, 1> m;    
        m(0, 0) = *dxC;    
        return m;
    }
    Matrix<float,3, 1> CLIPPER::w() const {    
        Matrix<float,3, 1> m;    
        m(0, 0) = *wd2_R;    
        m(1, 0) = *wd2_gmin;    
        m(2, 0) = *wd2;    
        return m;
    }
    Matrix<float,2, 1> CLIPPER::u() const {    
        Matrix<float,2, 1> m;    
        m(0, 0) = *uoutput;    
        m(1, 0) = *uinput;    
        return m;
    }
    Matrix<float,0, 0> CLIPPER::p() const {    
        Matrix<float,0, 0> m;    
        return m;
    }
    Matrix<float,3, 1> CLIPPER::vl() const {    
        Matrix<float,3, 1> m;    
        m(0, 0) = *dxC;    
        m(1, 0) = *wd2_R;    
        m(2, 0) = *wd2_gmin;    
        return m;
    }
    Matrix<float,1, 1> CLIPPER::vnl() const {    
        Matrix<float,1, 1> m;    
        m(0, 0) = *wd2;    
        return m;
    }
    Matrix<float,0, 0> CLIPPER::o() const {    
        Matrix<float,0, 0> m;    
        return m;
    }
    //==========================================================================
    // Mutators for Arguments, type = vector<float>
    void CLIPPER::set_x(vector<float> & v) {
        *xC = v[0];
    }
    void CLIPPER::set_dx(vector<float> & v) {
        *dxC = v[0];
    }
    void CLIPPER::set_w(vector<float> & v) {
        *wd2_R = v[0];
        *wd2_gmin = v[1];
        *wd2 = v[2];
    }
    void CLIPPER::set_u(vector<float> & v) {
        *uoutput = v[0];
        *uinput = v[1];
    }
    void CLIPPER::set_p(vector<float> & v) {
    }
    void CLIPPER::set_vl(vector<float> & v) {
        *dxC = v[0];
        *wd2_R = v[1];
        *wd2_gmin = v[2];
    }
    void CLIPPER::set_vnl(vector<float> & v) {
        *wd2 = v[0];
    }
    void CLIPPER::set_o(vector<float> & v) {
    }
    //==========================================================================
    // Mutators for Arguments, type = Matrix<float, n, m>
    void CLIPPER::set_x(Matrix<float, 1, 1> & m) {
        *xC = m(0, 0);
    }
    void CLIPPER::set_dx(Matrix<float, 1, 1> & m) {
        *dxC = m(0, 0);
    }
    void CLIPPER::set_w(Matrix<float, 3, 1> & m) {
        *wd2_R = m(0, 0);
        *wd2_gmin = m(1, 0);
        *wd2 = m(2, 0);
    }
    void CLIPPER::set_u(Matrix<float, 2, 1> & m) {
        *uoutput = m(0, 0);
        *uinput = m(1, 0);
    }
    void CLIPPER::set_p(Matrix<float, 0, 0> & m) {
    }
    void CLIPPER::set_vl(Matrix<float, 3, 1> & m) {
        *dxC = m(0, 0);
        *wd2_R = m(1, 0);
        *wd2_gmin = m(2, 0);
    }
    void CLIPPER::set_vnl(Matrix<float, 1, 1> & m) {
        *wd2 = m(0, 0);
    }
    void CLIPPER::set_o(Matrix<float, 0, 0> & m) {
    }
    //==========================================================================
    // Mutators for a single argument, types are float with int index
    void CLIPPER::set_x(float & value, unsigned int & index) {
        if(index == 0) {
            *xC = value;
        }
    }
    void CLIPPER::set_dx(float & value, unsigned int & index) {
        if(index == 0) {
            *dxC = value;
        }
    }
    void CLIPPER::set_w(float & value, unsigned int & index) {
        if(index == 0) {
            *wd2_R = value;
        }
        else if(index == 1) {
            *wd2_gmin = value;
        }
        else if(index == 2) {
            *wd2 = value;
        }
    }
    void CLIPPER::set_u(float & value, unsigned int & index) {
        if(index == 0) {
            *uoutput = value;
        }
        else if(index == 1) {
            *uinput = value;
        }
    }
    void CLIPPER::set_p(float & value, unsigned int & index) {
    }
    void CLIPPER::set_vl(float & value, unsigned int & index) {
        if(index == 0) {
            *dxC = value;
        }
        else if(index == 1) {
            *wd2_R = value;
        }
        else if(index == 2) {
            *wd2_gmin = value;
        }
    }
    void CLIPPER::set_vnl(float & value, unsigned int & index) {
        if(index == 0) {
            *wd2 = value;
        }
    }
    void CLIPPER::set_o(float & value, unsigned int & index) {
    }
    //==========================================================================
    // Functions Results Accessors (matrix)
    Matrix<float,0, 0> CLIPPER::ud_o() const {
        return _ud_o;
    }
    Matrix<float,3, 3> CLIPPER::jactempFll() const {
        return _jactempFll;
    }
    Matrix<float,3, 1> CLIPPER::Gl() const {
        return _Gl;
    }
    Matrix<float,1, 3> CLIPPER::jactempFnll() const {
        return _jactempFnll;
    }
    Matrix<float,1, 1> CLIPPER::Gnl() const {
        return _Gnl;
    }
    Matrix<float,3, 1> CLIPPER::jacGlnl() const {
        return _jacGlnl;
    }
    Matrix<float,1, 1> CLIPPER::jacGnlnl() const {
        return _jacGnlnl;
    }
    Matrix<float,1, 1> CLIPPER::dxH() const {
        return _dxH;
    }
    Matrix<float,3, 1> CLIPPER::z() const {
        return _z;
    }
    Matrix<float,2, 1> CLIPPER::y() const {
        return _y;
    }
    //==========================================================================
    // Functions Results Accessors (vector)
    vector<float> CLIPPER::ud_o_vector() const {    
        vector<float> v = vector<float>(0);    
        return v;
    }
    vector<float> CLIPPER::jactempFll_vector() const {    
        vector<float> v = vector<float>(3);    
        v[0] = _jactempFll(0, 0);    
        v[1] = _jactempFll(1, 0);    
        v[2] = _jactempFll(2, 0);    
        return v;
    }
    vector<float> CLIPPER::Gl_vector() const {    
        vector<float> v = vector<float>(3);    
        v[0] = _Gl(0, 0);    
        v[1] = _Gl(1, 0);    
        v[2] = _Gl(2, 0);    
        return v;
    }
    vector<float> CLIPPER::jactempFnll_vector() const {    
        vector<float> v = vector<float>(1);    
        v[0] = _jactempFnll(0, 0);    
        return v;
    }
    vector<float> CLIPPER::Gnl_vector() const {    
        vector<float> v = vector<float>(1);    
        v[0] = _Gnl(0, 0);    
        return v;
    }
    vector<float> CLIPPER::jacGlnl_vector() const {    
        vector<float> v = vector<float>(3);    
        v[0] = _jacGlnl(0, 0);    
        v[1] = _jacGlnl(1, 0);    
        v[2] = _jacGlnl(2, 0);    
        return v;
    }
    vector<float> CLIPPER::jacGnlnl_vector() const {    
        vector<float> v = vector<float>(1);    
        v[0] = _jacGnlnl(0, 0);    
        return v;
    }
    vector<float> CLIPPER::dxH_vector() const {    
        vector<float> v = vector<float>(1);    
        v[0] = _dxH(0, 0);    
        return v;
    }
    vector<float> CLIPPER::z_vector() const {    
        vector<float> v = vector<float>(3);    
        v[0] = _z(0, 0);    
        v[1] = _z(1, 0);    
        v[2] = _z(2, 0);    
        return v;
    }
    vector<float> CLIPPER::y_vector() const {    
        vector<float> v = vector<float>(2);    
        v[0] = _y(0, 0);    
        v[1] = _y(1, 0);    
        return v;
    }
    //==========================================================================
    // Functions Results Accessors (element)
    float CLIPPER::ud_o(unsigned int & index) const {    
        return _ud_o(index, 0);
    }
    float CLIPPER::jactempFll(unsigned int & index) const {    
        return _jactempFll(index, 0);
    }
    float CLIPPER::Gl(unsigned int & index) const {    
        return _Gl(index, 0);
    }
    float CLIPPER::jactempFnll(unsigned int & index) const {    
        return _jactempFnll(index, 0);
    }
    float CLIPPER::Gnl(unsigned int & index) const {    
        return _Gnl(index, 0);
    }
    float CLIPPER::jacGlnl(unsigned int & index) const {    
        return _jacGlnl(index, 0);
    }
    float CLIPPER::jacGnlnl(unsigned int & index) const {    
        return _jacGnlnl(index, 0);
    }
    float CLIPPER::dxH(unsigned int & index) const {    
        return _dxH(index, 0);
    }
    float CLIPPER::z(unsigned int & index) const {    
        return _z(index, 0);
    }
    float CLIPPER::y(unsigned int & index) const {    
        return _y(index, 0);
    }
    //==========================================================================
    // Oprations Results Accessors
    Matrix<float,1, 1> CLIPPER::ud_x() const {
        return _ud_x;
    }
    Matrix<float,3, 3> CLIPPER::ijactempFll() const {
        return _ijactempFll;
    }
    Matrix<float,3, 1> CLIPPER::ud_vl() const {
        return _ud_vl;
    }
    Matrix<float,1, 1> CLIPPER::Fnl() const {
        return _Fnl;
    }
    Matrix<float,1, 1> CLIPPER::jacFnl() const {
        return _jacFnl;
    }
    Matrix<float,1, 1> CLIPPER::ijacFnl() const {
        return _ijacFnl;
    }
    Matrix<float,1, 1> CLIPPER::save_Fnl() const {
        return _save_Fnl;
    }
    float CLIPPER::res_Fnl() const {
        return _res_Fnl;
    }
    float CLIPPER::step_Fnl() const {
        return _step_Fnl;
    }
    Matrix<float,1, 1> CLIPPER::ud_vnl() const {
        return _ud_vnl;
    }
    //==========================================================================
    // Oprations Results Accessors
    vector<float> CLIPPER::ud_x_vector() const {    
        vector<float> v = vector<float>(1);    
        v[0] = _ud_x(0, 0);    
        return v;
    }
    vector<float> CLIPPER::ud_vl_vector() const {    
        vector<float> v = vector<float>(3);    
        v[0] = _ud_vl(0, 0);    
        v[1] = _ud_vl(1, 0);    
        v[2] = _ud_vl(2, 0);    
        return v;
    }
    vector<float> CLIPPER::Fnl_vector() const {    
        vector<float> v = vector<float>(1);    
        v[0] = _Fnl(0, 0);    
        return v;
    }
    vector<float> CLIPPER::save_Fnl_vector() const {    
        vector<float> v = vector<float>(1);    
        v[0] = _save_Fnl(0, 0);    
        return v;
    }
    vector<float> CLIPPER::ud_vnl_vector() const {    
        vector<float> v = vector<float>(1);    
        v[0] = _ud_vnl(0, 0);    
        return v;
    }
    //==========================================================================
    // Default Constructor
    CLIPPER::CLIPPER(){    
        //==========================================================================
        // Functions Results Initialisation Data
        float ud_o_data[] = {};
        float jactempFll_data[] = {(*F_S), 0., 0., 0., 1, 0., 0., 0., 1};
        float Gl_data[] = {0., 0., 0.};
        float jactempFnll_data[] = {0., 0., -1.0/(*gmin)};
        float Gnl_data[] = {0.};
        float jacGlnl_data[] = {0., 0., 0.};
        float jacGnlnl_data[] = {1};
        float dxH_data[] = {0.};
        float z_data[] = {0., 0., 0.};
        float y_data[] = {0., 0.};    
        //==========================================================================
        // Functions Results Initialisation    
        _ud_o = Map<Matrix<float,0, 0>> (ud_o_data);    
        _jactempFll = Map<Matrix<float,3, 3>> (jactempFll_data);    
        _Gl = Map<Matrix<float,3, 1>> (Gl_data);    
        _jactempFnll = Map<Matrix<float,1, 3>> (jactempFnll_data);    
        _Gnl = Map<Matrix<float,1, 1>> (Gnl_data);    
        _jacGlnl = Map<Matrix<float,3, 1>> (jacGlnl_data);    
        _jacGnlnl = Map<Matrix<float,1, 1>> (jacGnlnl_data);    
        _dxH = Map<Matrix<float,1, 1>> (dxH_data);    
        _z = Map<Matrix<float,3, 1>> (z_data);    
        _y = Map<Matrix<float,2, 1>> (y_data);    
        //==========================================================================
        // Initialization    
        init();
    };
    //==========================================================================
    // Default Destructor
    CLIPPER::~CLIPPER(){
    };

//==========================================================================
// PRIVATE    
    //==========================================================================
    // Functions Results Updates
    void CLIPPER::ud_o_update(){
    };
    void CLIPPER::jactempFll_update(){
    };
    void CLIPPER::Gl_update(){
    _Gl(1, 0) = -1.0*(*uoutput);
    _Gl(2, 0) = 1.0*(*Is)*(exp((*wd2)/((*mu)*(*v0))) - 1) - 1.0*(*uoutput);
    };
    void CLIPPER::jactempFnll_update(){
    };
    void CLIPPER::Gnl_update(){
    _Gnl(0, 0) = (*wd2);
    };
    void CLIPPER::jacGlnl_update(){
    _jacGlnl(2, 0) = 1.0*(*Is)*exp((*wd2)/((*mu)*(*v0)))/((*mu)*(*v0));
    };
    void CLIPPER::jacGnlnl_update(){
    };
    void CLIPPER::dxH_update(){
    _dxH(0, 0) = 1.0*(0.5*(*dxC) + (*xC))/(*Csymbol);
    };
    void CLIPPER::z_update(){
    _z(0, 0) = (*Rd)*(*wd2_R);
    _z(1, 0) = (*wd2_gmin)/(*gmin);
    _z(2, 0) = (*Is)*(exp((*wd2)/((*mu)*(*v0))) - 1);
    };
    void CLIPPER::y_update(){
    _y(0, 0) = -1.0*(*Rd)*(*wd2_R) - 1.0*(*wd2_gmin)/(*gmin);
    };
    //==========================================================================
    // Oprations Results Updates
    void CLIPPER::ud_x_update(){
        _ud_x = (x()) + (dx());
    };
    void CLIPPER::ijactempFll_update(){
        _ijactempFll = (jactempFll()).inverse();
    };
    void CLIPPER::ud_vl_update(){
        _ud_vl = (ijactempFll())*((-1.0)*(Gl()));
    };
    void CLIPPER::Fnl_update(){
        _Fnl = (Gnl()) + ((jactempFnll())*((ijactempFll())*((-1)*(Gl()))));
    };
    void CLIPPER::jacFnl_update(){
        _jacFnl = (jacGnlnl()) + ((jactempFnll())*((ijactempFll())*((-1)*(jacGlnl()))));
    };
    void CLIPPER::ijacFnl_update(){
        _ijacFnl = (jacFnl()).inverse();
    };
    void CLIPPER::save_Fnl_update(){
        _save_Fnl = Fnl();
    };
    void CLIPPER::res_Fnl_update(){
        _res_Fnl = sqrt((Fnl()).dot(Fnl()));
    };
    void CLIPPER::step_Fnl_update(){
        _step_Fnl = sqrt(((Fnl()) + ((-1.0)*(save_Fnl()))).dot((Fnl()) + ((-1.0)*(save_Fnl()))));
    };
    void CLIPPER::ud_vnl_update(){
        _ud_vnl = (vnl()) + ((-1.0)*((ijacFnl())*(Fnl())));
    };
    //==========================================================================
    // Initialization
    void CLIPPER::init(){    
        //==========================================================================
        // Arguments Initialisation Data
        vector<float> x_data = {0.};
        vector<float> dx_data = {0.};
        vector<float> w_data = {0., 0., 0.};
        vector<float> u_data = {0., 0.};
        vector<float> p_data = {};
        vector<float> o_data = {};
        //==========================================================================
        // Arguments Initialisation
        set_x(x_data);
        set_dx(dx_data);
        set_w(w_data);
        set_u(u_data);
        set_p(p_data);
        set_o(o_data);
        //==========================================================================
        // Functions Results Initialisation
        ud_o_update();
        jactempFll_update();
        Gl_update();
        jactempFnll_update();
        Gnl_update();
        jacGlnl_update();
        jacGnlnl_update();
        dxH_update();
        z_update();
        y_update();
        //==========================================================================
        // Operations Results Initialisation
        ud_x_update();
        ijactempFll_update();
        Fnl_update();
        res_Fnl_update();
        save_Fnl_update();
        jacFnl_update();
        ijacFnl_update();
        ud_vnl_update();
        step_Fnl_update();
        ud_vl_update();
    };